name: Update GitHub Metrics

on:
  schedule:
    - cron: "17 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: snehapankhi05

          base: header, activity, community, repositories

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
